### PR TITLE
Add Debian and NeuroDebian to Resources

### PR DESCRIPTION
**Pull request by yarikoptic**
That will be the approach we might end up using to establish close to 100% identical environment for the [paper 18](https://github.com/ReScience/ten-years/issues/1#issuecomment-548780132) submission.

### CODE REVIEW

**Comment by rougier** [comment]
You're right, Debian seems a good resource to add (maybe not NeuroDebian since the challenge is open to any domain).

**Comment by yarikoptic** [comment]
Feel welcome to tune the way you like. 
Note: even though we do target Neuroscience in NeuroDebian, we did package and provided backports of generic tools such as pandas, scikit-learn, htcondor etc, so users weren't limited to Neuro domain. I saw our pymvpa (also neuro oriented) used on Arctic robots etc.

**Comment by yarikoptic** [comment]
Adjusted my patch by merging added in master mentioning of debian. note that although reproducible builds are **really** cool, they aren't really of help to reproduce 10 year old results/environments.  archive/snapshots and debootstrap -- that what does make it useful.
I also stripped mentioning of NeuroDebian away.

**Comment by rougier** [comment]
I did not see this was a PR originally, sorry for the mess. I need to modify [ten-years.md](https://github.com/ReScience/rescience.github.io/blob/sources/ten-years.md) as well.

**Pull request merged**
